//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTeamProject.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicationDetail
    {
        public int appID { get; set; }
        public int userID { get; set; }
        public int jobID { get; set; }
        public System.DateTime applicationDate { get; set; }
    
        public virtual user user { get; set; }
        public virtual job job { get; set; }
    }
}
