//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTeamProject.Datas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class wpf_databaseEntities : DbContext
    {
        public wpf_databaseEntities()
            : base("name=wpf_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<applicationDetail> applicationDetails { get; set; }
        public virtual DbSet<job> jobs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<userInfo> userInfoes { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
