//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTeamProject.Datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInfo
    {
        public int userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public long phone { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public int experience { get; set; }
        public string skill { get; set; }
        public string position { get; set; }
    
        public virtual user user { get; set; }
    }
}
